spool gen_hem_person_name_history_dl
@dl_hem_person_name_history_tab.sql
@s_dl_hem_person_name_history.pks
@s_dl_hem_person_name_history.pkb
@hem_person_name_history_indexes.sql
@hem_person_name_history_dlas.sql
@hem_person_name_history_grants.sql
@hd2_errs_in.sql
spool off