--------------------------------------------------------
--  File created - Tuesday 04-06-2019
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DL_HRA_WAT_CHRG_CALC_AUDITS
--------------------------------------------------------
CREATE TABLE DL_HRA_WAT_CHRG_CALC_AUDITS
(
  LWCCA_DLB_BATCH_ID              VARCHAR2(30 BYTE) NOT NULL,
  LWCCA_DL_SEQNO                  NUMBER(10)    NOT NULL,
  LWCCA_DL_LOAD_STATUS            VARCHAR2(1 BYTE) NOT NULL,
  LWCCA_REFNO                     NUMBER(10)    NOT NULL,
  LWCCA_RAC_PAYREF                VARCHAR2(25 BYTE) NOT NULL,
  LWCCA_BILL_PERIOD_START_DATE    DATE          NOT NULL,
  LWCCA_BILL_PERIOD_END_DATE      DATE          NOT NULL,
  LWCCA_ACTUAL_CHARGE_AMOUNT      NUMBER(10,3)  NOT NULL,
  LWCCA_ADJUSTED_WEEKLY_CHARGE    NUMBER(10,3)  NOT NULL,
  LWCCA_CHARGE_EFFECTIVE_DATE     DATE          NOT NULL,
  LWCCA_TOTAL_ADJUSTMENT          NUMBER(10,3)  NOT NULL,
  LWCCA_WKLY_ADJUSTMNT_COMPONENT  NUMBER(10,3)  NOT NULL,
  LWCCA_TOTAL_UNADJ_PREV_CHARGES  NUMBER(10,3)  NOT NULL,
  LWCCA_NEW_UNADJ_WEEKLY_CHARGE   NUMBER(10,3)  NOT NULL,
  LWCCA_NUMBER_OF_WEEKS           NUMBER(7,4)   NOT NULL,
  LWCCA_SCO_CODE                  VARCHAR2(3 BYTE) NOT NULL,
  LWCCA_CREATED_BY                VARCHAR2(30 BYTE),
  LWCCA_CREATED_DATE              DATE,
  LWCCA_CHARGES_WAIVED_AMOUNT     NUMBER(5,3),
  LWCCA_UNADJ_WEEKLY_CHARGE_SP_1  NUMBER(10,3),
  LWCCA_TOTAL_UNADJ_CHARGE_SP_1   NUMBER(10,3),
  LWCCA_UNADJ_WEEKLY_CHARGE_SP_2  NUMBER(10,3),
  LWCCA_TOTAL_UNADJ_CHARGE_SP_2   NUMBER(10,3),
  LWCCA_RECON_ACCT_WEEKS_TO_DATE  NUMBER(7,4),
  LWCCA_RECON_ACCT_PCT_CHG_TODT   NUMBER(10,3),
  LWCCA_RECON_EXTRAPOLATED_ACT    NUMBER(10,3),
  LWCCA_RECON_APPLIED_CREDIT_ADJ  NUMBER(10,3),
  LWCCA_RECON_TOTAL_ADJUSTMENT    NUMBER(10,3),
  LWCCA_MODIFIED_DATE             DATE,
  LWCCA_MODIFIED_BY               VARCHAR2(30 BYTE),
  LWCCA_TYPE                      VARCHAR2(10 BYTE),
  LWCCA_CURR_ASSESSMENT_REF       VARCHAR2(20 BYTE), 
  WAUD_BILL_PERIOD_START_DATE     DATE, 
  WAUD_BILL_PERIOD_END_DATE       DATE,
  WAUD_RCCO_CODE                  VARCHAR2(10 BYTE),
  LWCCA_ADDITIONAL_1              VARCHAR2(30 BYTE),
  LWCCA_ADDITIONAL_2              VARCHAR2(30 BYTE),
  LWCCA_ADDITIONAL_3              VARCHAR2(30 BYTE),
  LWCCA_ADDITIONAL_4              VARCHAR2(30 BYTE),
  LWCCA_ADDITIONAL_5              VARCHAR2(30 BYTE),
  LWCCA_ADDITIONAL_6              VARCHAR2(30 BYTE),
  LWCCA_ADDITIONAL_7              VARCHAR2(30 BYTE),
  LWCCA_ADDITIONAL_8              VARCHAR2(30 BYTE),
  LWCCA_ADDITIONAL_9              VARCHAR2(30 BYTE),
  LWCCA_ADDITIONAL_10             VARCHAR2(30 BYTE),
  LWCCA_ADDITIONAL_11             VARCHAR2(30 BYTE),
  LWCCA_ADDITIONAL_12             VARCHAR2(30 BYTE),
  LWCCA_ADDITIONAL_13             VARCHAR2(30 BYTE),
  LWCCA_ADDITIONAL_14             VARCHAR2(30 BYTE),
  LWCCA_ADDITIONAL_15             VARCHAR2(30 BYTE),
  LWCCA_ADDITIONAL_16             VARCHAR2(30 BYTE),
  LWCCA_ADDITIONAL_17             VARCHAR2(30 BYTE),
  LWCCA_ADDITIONAL_18             VARCHAR2(30 BYTE),
  LWCCA_ADDITIONAL_19             VARCHAR2(30 BYTE),
  LWCCA_ADDITIONAL_20             VARCHAR2(30 BYTE),
  LWCCA_ADDITIONAL_21             VARCHAR2(2000 BYTE)
) TABLESPACE "TABLES" ;

CREATE UNIQUE INDEX HOU.PK_DL_WAT_CHRG_CALC_AUDITS ON HOU.DL_HRA_WAT_CHRG_CALC_AUDITS
(LWCCA_DLB_BATCH_ID, LWCCA_DL_SEQNO) TABLESPACE "INDEXES" ;

CREATE OR REPLACE PUBLIC SYNONYM DL_HRA_WAT_CHRG_CALC_AUDITS FOR HOU.DL_HRA_WAT_CHRG_CALC_AUDITS;

GRANT DELETE, INSERT, SELECT, UPDATE ON HOU.DL_HRA_WAT_CHRG_CALC_AUDITS TO FSC;
GRANT DELETE, INSERT, SELECT, UPDATE ON HOU.DL_HRA_WAT_CHRG_CALC_AUDITS TO HOU_FULL;
