load data
APPEND
into table DL_HRA_LWR_ASSESS_VAL_ERRORS
fields terminated by "," optionally enclosed by '"'
trailing nullcols
(
 LASVE_DLB_BATCH_ID          	CONSTANT "$batch_no",
 LASVE_DL_SEQNO              	RECNUM,
 LASVE_DL_LOAD_STATUS        	CONSTANT "L",
 LASVE_LWRB_REFNO		CHAR "rtrim(:LASVE_LWRB_REFNO)",
 LASVE_WRA_CURR_ASSESSMENT_REF 	CHAR "rtrim(:LASVE_WRA_CURR_ASSESSMENT_REF)",
 LWRA_RATE_PERIOD_START_DATE	DATE "DD-MON-YYYY HH24:MI:SS" NULLIF LWRA_RATE_PERIOD_START_DATE=blanks,
 LWRA_RATE_PERIOD_END_DATE	DATE "DD-MON-YYYY HH24:MI:SS" NULLIF LWRA_RATE_PERIOD_END_DATE=blanks,
 LASVE_FLVE_CODE		CHAR "rtrim(:LASVE_FLVE_CODE)",
 LASVE_CREATED_BY            	CHAR "rtrim(:LASVE_CREATED_BY)",
 LASVE_CREATED_DATE          	DATE "DD-MON-YYYY HH24:MI:SS" NULLIF LASVE_CREATED_DATE=blanks
)

