--------------------------------------------------------
--  File created - Wednesday-September-26-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DL_HRA_LWR_APPORTND_ASS_DETS
--------------------------------------------------------

  CREATE TABLE "HOU"."DL_HRA_LWR_APPORTND_ASS_DETS" 
   (	"LAAD_DLB_BATCH_ID" VARCHAR2(30 BYTE), 
	"LAAD_DL_SEQNO" NUMBER(10,0), 
	"LAAD_DL_LOAD_STATUS" VARCHAR2(1 BYTE), 
	"LAAD_REFNO" NUMBER(10,0), 
	"LAAD_LWRB_REFNO" NUMBER(10,0), 
	"LAAD_WRA_CURR_ASSESSMENT_REF" VARCHAR2(20 BYTE), 
	"LWRA_RATE_PERIOD_START_DATE" DATE, 
	"LWRA_RATE_PERIOD_END_DATE" DATE, 
	"LAAD_PRO_PROPREF" VARCHAR2(25 BYTE), 
	"LAAD_AMOUNT" NUMBER(10,2), 
	"LAAD_CREATED_BY" VARCHAR2(30 BYTE), 
	"LAAD_CREATED_DATE" DATE, 
	"LAAD_RCCO_CODE" VARCHAR2(10 BYTE), 
	"LWAUD_BILL_PERIOD_START_DATE" DATE, 
	"LWAUD_BILL_PERIOD_END_DATE" DATE, 
	"LAAD_RAAM_SEQ_NO" NUMBER(9,0), 
	"LAAD_LPRD_LWPR_DOC_NUM" NUMBER(15,0), 
	"LAAD_LPRD_SEQ" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TABLES" ;
--------------------------------------------------------
--  DDL for Index PK_DL_LWR_APPORTND_ASS_DETS
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOU"."PK_DL_LWR_APPORTND_ASS_DETS" ON "HOU"."DL_HRA_LWR_APPORTND_ASS_DETS" ("LAAD_DLB_BATCH_ID", "LAAD_DL_SEQNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INDEXES" ;
--------------------------------------------------------
--  Constraints for Table DL_HRA_LWR_APPORTND_ASS_DETS
--------------------------------------------------------

  ALTER TABLE "HOU"."DL_HRA_LWR_APPORTND_ASS_DETS" MODIFY ("LWAUD_BILL_PERIOD_END_DATE" NOT NULL ENABLE);
  ALTER TABLE "HOU"."DL_HRA_LWR_APPORTND_ASS_DETS" MODIFY ("LWAUD_BILL_PERIOD_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "HOU"."DL_HRA_LWR_APPORTND_ASS_DETS" MODIFY ("LAAD_AMOUNT" NOT NULL ENABLE);
  ALTER TABLE "HOU"."DL_HRA_LWR_APPORTND_ASS_DETS" MODIFY ("LAAD_PRO_PROPREF" NOT NULL ENABLE);
  ALTER TABLE "HOU"."DL_HRA_LWR_APPORTND_ASS_DETS" MODIFY ("LWRA_RATE_PERIOD_END_DATE" NOT NULL ENABLE);
  ALTER TABLE "HOU"."DL_HRA_LWR_APPORTND_ASS_DETS" MODIFY ("LWRA_RATE_PERIOD_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "HOU"."DL_HRA_LWR_APPORTND_ASS_DETS" MODIFY ("LAAD_WRA_CURR_ASSESSMENT_REF" NOT NULL ENABLE);
  ALTER TABLE "HOU"."DL_HRA_LWR_APPORTND_ASS_DETS" MODIFY ("LAAD_LWRB_REFNO" NOT NULL ENABLE);
  ALTER TABLE "HOU"."DL_HRA_LWR_APPORTND_ASS_DETS" MODIFY ("LAAD_REFNO" NOT NULL ENABLE);
  ALTER TABLE "HOU"."DL_HRA_LWR_APPORTND_ASS_DETS" MODIFY ("LAAD_DL_LOAD_STATUS" NOT NULL ENABLE);
  ALTER TABLE "HOU"."DL_HRA_LWR_APPORTND_ASS_DETS" MODIFY ("LAAD_DL_SEQNO" NOT NULL ENABLE);
  ALTER TABLE "HOU"."DL_HRA_LWR_APPORTND_ASS_DETS" MODIFY ("LAAD_DLB_BATCH_ID" NOT NULL ENABLE);
