--------------------------------------------------------
--  File created - Wednesday-September-26-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DL_HRA_LWR_ASSESSMENTS
--------------------------------------------------------

  CREATE TABLE "HOU"."DL_HRA_LWR_ASSESSMENTS" 
   (	"LWRA_DLB_BATCH_ID" VARCHAR2(30 BYTE), 
	"LWRA_DL_SEQNO" NUMBER(10,0), 
	"LWRA_DL_LOAD_STATUS" VARCHAR2(1 BYTE), 
	"LWRA_REFNO" NUMBER(10,0), 
	"LWRA_LWRB_REFNO" NUMBER(10,0), 
	"LWRA_TYPE" VARCHAR2(4 BYTE), 
	"LWRA_SCO_CODE" VARCHAR2(3 BYTE), 
	"LWRA_RATE_PERIOD_START_DATE" DATE, 
	"LWRA_RATE_PERIOD_END_DATE" DATE, 
	"LWRA_CURRENT_ASSESSMENT_REF" VARCHAR2(20 BYTE), 
	"LWRA_LOT_NUMBER" VARCHAR2(4 BYTE), 
	"LWRA_PLAN_NUMBER" NUMBER(10,0), 
	"LWRA_PLAN_TYPE" VARCHAR2(10 BYTE), 
	"LWRA_TOTAL_PAYABLE_AMOUNT" NUMBER(10,2), 
	"LWRA_CR_DR_INDICATOR" VARCHAR2(2 BYTE), 
	"LWRA_ADDRESS" VARCHAR2(255 BYTE), 
	"LWRA_CREATED_BY" VARCHAR2(30 BYTE), 
	"LWRA_CREATED_DATE" DATE, 
	"LWRA_SECTION_NUMBER" VARCHAR2(4 BYTE), 
	"LWRA_VG_INSERT_NUMBER" VARCHAR2(8 BYTE), 
	"LWRA_VG_DISTRICT_NUMBER" NUMBER(3,0), 
	"LWRA_LAND_RATEABLE_VALUE" NUMBER(10,2), 
	"LWRA_INSTALMENT_AMOUNT" NUMBER(8,2), 
	"LWRA_INSTALMENT_DUE_DATE" DATE, 
	"LWRA_PREV_ASSESSMENT_REF" VARCHAR2(20 BYTE), 
	"LWRA_NO_OF_EXTRA_CHARGES" NUMBER(2,0), 
	"LWRA_INSTALMENT_1_AMOUNT" NUMBER(8,2), 
	"LWRA_INSTALMENT_2_AMOUNT" NUMBER(8,2), 
	"LWRA_INSTALMENT_3_AMOUNT" NUMBER(8,2), 
	"LWRA_INSTALMENT_4_AMOUNT" NUMBER(8,2), 
	"LWRA_CATEGORY_RECORD_COUNT" NUMBER(3,0), 
	"LWRA_CURRENT_ANNUAL_RATES" NUMBER(10,2), 
	"LWRA_FAOR_CODE" VARCHAR2(10 BYTE), 
	"LWRA_LGA_CODE" VARCHAR2(3 BYTE), 
	"LWRA_MODIFIED_BY" VARCHAR2(30 BYTE), 
	"LWRA_MODIFIED_DATE" DATE, 
	"LWRA_PRO_PROPREF" VARCHAR2(25 BYTE), 
	"LWRA_PREV_LWRA_REFNO" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TABLES" ;
--------------------------------------------------------
--  DDL for Index PK_DL_LWR_ASSESSMENTS
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOU"."PK_DL_LWR_ASSESSMENTS" ON "HOU"."DL_HRA_LWR_ASSESSMENTS" ("LWRA_DLB_BATCH_ID", "LWRA_DL_SEQNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INDEXES" ;
--------------------------------------------------------
--  Constraints for Table DL_HRA_LWR_ASSESSMENTS
--------------------------------------------------------

  ALTER TABLE "HOU"."DL_HRA_LWR_ASSESSMENTS" MODIFY ("LWRA_ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "HOU"."DL_HRA_LWR_ASSESSMENTS" MODIFY ("LWRA_CR_DR_INDICATOR" NOT NULL ENABLE);
  ALTER TABLE "HOU"."DL_HRA_LWR_ASSESSMENTS" MODIFY ("LWRA_TOTAL_PAYABLE_AMOUNT" NOT NULL ENABLE);
  ALTER TABLE "HOU"."DL_HRA_LWR_ASSESSMENTS" MODIFY ("LWRA_PLAN_TYPE" NOT NULL ENABLE);
  ALTER TABLE "HOU"."DL_HRA_LWR_ASSESSMENTS" MODIFY ("LWRA_PLAN_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "HOU"."DL_HRA_LWR_ASSESSMENTS" MODIFY ("LWRA_LOT_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "HOU"."DL_HRA_LWR_ASSESSMENTS" MODIFY ("LWRA_CURRENT_ASSESSMENT_REF" NOT NULL ENABLE);
  ALTER TABLE "HOU"."DL_HRA_LWR_ASSESSMENTS" MODIFY ("LWRA_RATE_PERIOD_END_DATE" NOT NULL ENABLE);
  ALTER TABLE "HOU"."DL_HRA_LWR_ASSESSMENTS" MODIFY ("LWRA_RATE_PERIOD_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "HOU"."DL_HRA_LWR_ASSESSMENTS" MODIFY ("LWRA_SCO_CODE" NOT NULL ENABLE);
  ALTER TABLE "HOU"."DL_HRA_LWR_ASSESSMENTS" MODIFY ("LWRA_TYPE" NOT NULL ENABLE);
  ALTER TABLE "HOU"."DL_HRA_LWR_ASSESSMENTS" MODIFY ("LWRA_LWRB_REFNO" NOT NULL ENABLE);
  ALTER TABLE "HOU"."DL_HRA_LWR_ASSESSMENTS" MODIFY ("LWRA_DL_LOAD_STATUS" NOT NULL ENABLE);
  ALTER TABLE "HOU"."DL_HRA_LWR_ASSESSMENTS" MODIFY ("LWRA_DL_SEQNO" NOT NULL ENABLE);
  ALTER TABLE "HOU"."DL_HRA_LWR_ASSESSMENTS" MODIFY ("LWRA_DLB_BATCH_ID" NOT NULL ENABLE);
