--------------------------------------------------------
--  File created - Wednesday-September-26-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DL_HRA_LWR_WATER_USAGE_DETS
--------------------------------------------------------

  CREATE TABLE "HOU"."DL_HRA_LWR_WATER_USAGE_DETS" 
   (	"LWAUD_DLB_BATCH_ID" VARCHAR2(30 BYTE), 
	"LWAUD_DL_SEQNO" NUMBER(10,0), 
	"LWAUD_DL_LOAD_STATUS" VARCHAR2(1 BYTE), 
	"LWAUD_REFNO" NUMBER(10,0), 
	"LWAUD_LWRB_REFNO" NUMBER(10,0), 
	"LWAUD_WRA_CURR_ASSESSMENT_REF" VARCHAR2(20 BYTE), 
	"LWRA_RATE_PERIOD_START_DATE" DATE, 
	"LWRA_RATE_PERIOD_END_DATE" DATE, 
	"LWAUD_BILL_PERIOD_START_DATE" DATE, 
	"LWAUD_BILL_PERIOD_END_DATE" DATE, 
	"LWAUD_CATEGORY_RATE_AMOUNT" NUMBER(10,2), 
	"LWAUD_CR_DR_INDICATOR" VARCHAR2(2 BYTE), 
	"LWAUD_CHARGEABLE_WATER_USAGE" NUMBER(9,0), 
	"LWAUD_SCO_CODE" VARCHAR2(3 BYTE), 
	"LWAUD_RCCO_CODE" VARCHAR2(10 BYTE), 
	"LWAUD_CURRENT_METER_READING" NUMBER(9,0), 
	"LWAUD_CHARGE_RATE_LEVEL_1" NUMBER(10,2), 
	"LWAUD_CONSUMPTION_LEVEL_1" NUMBER(9,0), 
	"LWAUD_DEBIT_AMOUNT_LEVEL_1" NUMBER(10,2), 
	"LWAUD_CREATED_BY" VARCHAR2(30 BYTE), 
	"LWAUD_CREATED_DATE" DATE, 
	"LWAUD_WATER_METER_NUMBER" VARCHAR2(20 BYTE), 
	"LWAUD_PREV_METER_READING" NUMBER(9,0), 
	"LWAUD_DAYS_SINCE_LAST_MTR_READ" NUMBER(5,0), 
	"LWAUD_CHARGE_RATE_LEVEL_2" NUMBER(10,2), 
	"LWAUD_CONSUMPTION_LEVEL_2" NUMBER(9,0), 
	"LWAUD_DEBIT_AMOUNT_LEVEL_2" NUMBER(10,2), 
	"LWAUD_CHARGE_RATE_LEVEL_3" NUMBER(10,2), 
	"LWAUD_CONSUMPTION_LEVEL_3" NUMBER(9,0), 
	"LWAUD_DEBIT_AMOUNT_LEVEL_3" NUMBER(10,2), 
	"LWAUD_CHARGE_RATE_LEVEL_4" NUMBER(10,2), 
	"LWAUD_CONSUMPTION_LEVEL_4" NUMBER(9,0), 
	"LWAUD_DEBIT_AMOUNT_LEVEL_4" NUMBER(10,2), 
	"LWAUD_REJECTED_BY" VARCHAR2(30 BYTE), 
	"LWAUD_REJECTED_DATE" DATE, 
	"LWAUD_HRV_WURR_CODE" VARCHAR2(10 BYTE), 
	"LWAUD_MODIFIED_BY" VARCHAR2(30 BYTE), 
	"LWAUD_MODIFIED_DATE" DATE, 
	"LWAUD_COMMENTS" VARCHAR2(240 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TABLES" ;
--------------------------------------------------------
--  DDL for Index PK_DL_LWR_WATER_USAGE_DETAILS
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOU"."PK_DL_LWR_WATER_USAGE_DETAILS" ON "HOU"."DL_HRA_LWR_WATER_USAGE_DETS" ("LWAUD_DLB_BATCH_ID", "LWAUD_DL_SEQNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INDEXES" ;
--------------------------------------------------------
--  Constraints for Table DL_HRA_LWR_WATER_USAGE_DETS
--------------------------------------------------------

  ALTER TABLE "HOU"."DL_HRA_LWR_WATER_USAGE_DETS" MODIFY ("LWAUD_CURRENT_METER_READING" NOT NULL ENABLE);
  ALTER TABLE "HOU"."DL_HRA_LWR_WATER_USAGE_DETS" MODIFY ("LWAUD_RCCO_CODE" NOT NULL ENABLE);
  ALTER TABLE "HOU"."DL_HRA_LWR_WATER_USAGE_DETS" MODIFY ("LWAUD_SCO_CODE" NOT NULL ENABLE);
  ALTER TABLE "HOU"."DL_HRA_LWR_WATER_USAGE_DETS" MODIFY ("LWAUD_CHARGEABLE_WATER_USAGE" NOT NULL ENABLE);
  ALTER TABLE "HOU"."DL_HRA_LWR_WATER_USAGE_DETS" MODIFY ("LWAUD_CR_DR_INDICATOR" NOT NULL ENABLE);
  ALTER TABLE "HOU"."DL_HRA_LWR_WATER_USAGE_DETS" MODIFY ("LWAUD_CATEGORY_RATE_AMOUNT" NOT NULL ENABLE);
  ALTER TABLE "HOU"."DL_HRA_LWR_WATER_USAGE_DETS" MODIFY ("LWAUD_BILL_PERIOD_END_DATE" NOT NULL ENABLE);
  ALTER TABLE "HOU"."DL_HRA_LWR_WATER_USAGE_DETS" MODIFY ("LWAUD_BILL_PERIOD_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "HOU"."DL_HRA_LWR_WATER_USAGE_DETS" MODIFY ("LWRA_RATE_PERIOD_END_DATE" NOT NULL ENABLE);
  ALTER TABLE "HOU"."DL_HRA_LWR_WATER_USAGE_DETS" MODIFY ("LWRA_RATE_PERIOD_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "HOU"."DL_HRA_LWR_WATER_USAGE_DETS" MODIFY ("LWAUD_WRA_CURR_ASSESSMENT_REF" NOT NULL ENABLE);
  ALTER TABLE "HOU"."DL_HRA_LWR_WATER_USAGE_DETS" MODIFY ("LWAUD_LWRB_REFNO" NOT NULL ENABLE);
  ALTER TABLE "HOU"."DL_HRA_LWR_WATER_USAGE_DETS" MODIFY ("LWAUD_DL_LOAD_STATUS" NOT NULL ENABLE);
  ALTER TABLE "HOU"."DL_HRA_LWR_WATER_USAGE_DETS" MODIFY ("LWAUD_DL_SEQNO" NOT NULL ENABLE);
  ALTER TABLE "HOU"."DL_HRA_LWR_WATER_USAGE_DETS" MODIFY ("LWAUD_DLB_BATCH_ID" NOT NULL ENABLE);
