--------------------------------------------------------
--  File created - Wednesday-September-26-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DL_HRA_LWR_BATCHES
--------------------------------------------------------

  CREATE TABLE "HOU"."DL_HRA_LWR_BATCHES" 
   (	"LWRB_DLB_BATCH_ID" VARCHAR2(30 BYTE), 
	"LWRB_DL_SEQNO" NUMBER(10,0), 
	"LWRB_DL_LOAD_STATUS" VARCHAR2(1 BYTE), 
	"LWRB_REFNO" NUMBER(10,0), 
	"LWRB_BATCH_TYPE" VARCHAR2(3 BYTE), 
	"LWRB_SCO_CODE" VARCHAR2(3 BYTE), 
	"LWRB_LOAD_FROM_FILE_IND" VARCHAR2(1 BYTE), 
	"LWRB_CREATED_BY" VARCHAR2(30 BYTE), 
	"LWRB_CREATED_DATE" DATE, 
	"LWRB_IPP_SHORTNAME" VARCHAR2(10 BYTE), 
	"LWRB_IPT_CODE" VARCHAR2(10 BYTE), 
	"LWRB_AUTHORITY_BATCH_DATE" DATE, 
	"LWRB_AUTHORITY_BATCH_NUMBER" VARCHAR2(10 BYTE), 
	"LWRB_AUTH_RECEIPT_NUMBER" VARCHAR2(80 BYTE), 
	"LWRB_FILENAME" VARCHAR2(240 BYTE), 
	"LWRB_LOADED_DATE" DATE, 
	"LWRB_LARS_FLRS_CODE" VARCHAR2(10 BYTE), 
	"LWRB_LARS_YEAR" NUMBER(4,0), 
	"LWRB_INSTALMENT_NUMBER" NUMBER(3,0), 
	"LWRB_LWRB_REFNO" NUMBER(10,0), 
	"LWRB_CLAIM_TYPE" VARCHAR2(10 BYTE), 
	"LWRB_CLAIM_DESCRIPTION" VARCHAR2(240 BYTE), 
	"LWRB_CLOSED_BY" VARCHAR2(30 BYTE), 
	"LWRB_CLOSED_DATE" DATE, 
	"LWRB_APPROVED_BY" VARCHAR2(30 BYTE), 
	"LWRB_APPROVED_DATE" DATE, 
	"LWRB_CHEQUE_DATE" DATE, 
	"LWRB_CHEQUE_NUMBER" VARCHAR2(40 BYTE), 
	"LWRB_DOCUMENT_DATE" DATE, 
	"LWRB_DOCUMENT_NUMBER" VARCHAR2(40 BYTE), 
	"LWRB_REOPENED_BY" VARCHAR2(30 BYTE), 
	"LWRB_REOPENED_DATE" DATE, 
	"LWRB_CANCELLED_BY" VARCHAR2(30 BYTE), 
	"LWRB_CANCELLED_DATE" DATE, 
	"LWRB_FBCR_CODE" VARCHAR2(10 BYTE), 
	"LWRB_MODIFIED_BY" VARCHAR2(30 BYTE), 
	"LWRB_MODIFIED_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TABLES" ;
--------------------------------------------------------
--  DDL for Index PK_DL_LWR_BATCHES
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOU"."PK_DL_LWR_BATCHES" ON "HOU"."DL_HRA_LWR_BATCHES" ("LWRB_DLB_BATCH_ID", "LWRB_DL_SEQNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INDEXES" ;
--------------------------------------------------------
--  Constraints for Table DL_HRA_LWR_BATCHES
--------------------------------------------------------

  ALTER TABLE "HOU"."DL_HRA_LWR_BATCHES" MODIFY ("LWRB_IPT_CODE" NOT NULL ENABLE);
  ALTER TABLE "HOU"."DL_HRA_LWR_BATCHES" MODIFY ("LWRB_IPP_SHORTNAME" NOT NULL ENABLE);
  ALTER TABLE "HOU"."DL_HRA_LWR_BATCHES" MODIFY ("LWRB_SCO_CODE" NOT NULL ENABLE);
  ALTER TABLE "HOU"."DL_HRA_LWR_BATCHES" MODIFY ("LWRB_BATCH_TYPE" NOT NULL ENABLE);
  ALTER TABLE "HOU"."DL_HRA_LWR_BATCHES" MODIFY ("LWRB_REFNO" NOT NULL ENABLE);
  ALTER TABLE "HOU"."DL_HRA_LWR_BATCHES" MODIFY ("LWRB_DL_LOAD_STATUS" NOT NULL ENABLE);
  ALTER TABLE "HOU"."DL_HRA_LWR_BATCHES" MODIFY ("LWRB_DL_SEQNO" NOT NULL ENABLE);
  ALTER TABLE "HOU"."DL_HRA_LWR_BATCHES" MODIFY ("LWRB_DLB_BATCH_ID" NOT NULL ENABLE);
