--------------------------------------------------------
--  File created - Wednesday-September-26-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DL_HRA_LWR_RATE_ASSESS_DETS
--------------------------------------------------------

  CREATE TABLE "HOU"."DL_HRA_LWR_RATE_ASSESS_DETS" 
   (	"LRAD_DLB_BATCH_ID" VARCHAR2(30 BYTE), 
	"LRAD_DL_SEQNO" NUMBER(10,0), 
	"LRAD_DL_LOAD_STATUS" VARCHAR2(1 BYTE), 
	"LRAD_REFNO" NUMBER(10,0), 
	"LRAD_LWRB_REFNO" NUMBER(10,0), 
	"LRAD_WRA_CURR_ASSESSMENT_REF" VARCHAR2(20 BYTE), 
	"LWRA_RATE_PERIOD_START_DATE" DATE, 
	"LWRA_RATE_PERIOD_END_DATE" DATE, 
	"LRAD_CLASS_CODE" VARCHAR2(4 BYTE), 
	"LRAD_RCCO_CODE" VARCHAR2(10 BYTE), 
	"LRAD_CATEGORY_RATE_AMOUNT" NUMBER(10,2), 
	"LRAD_CR_DR_INDICATOR" VARCHAR2(2 BYTE), 
	"LRAD_CREATED_BY" VARCHAR2(30 BYTE), 
	"LRAD_CREATED_DATE" DATE, 
	"LRAD_CATEGORY_START_DATE" DATE, 
	"LRAD_CATEGORY_END_DATE" DATE, 
	"LRAD_COMMENTS" VARCHAR2(240 BYTE), 
	"LRAD_MODIFIED_BY" VARCHAR2(30 BYTE), 
	"LRAD_MODIFIED_DATE" DATE, 
	"LRAD_RAAM_SEQ_NO" NUMBER(9,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TABLES" ;
--------------------------------------------------------
--  DDL for Index PK_DL_LWR_RATE_ASSESS_DETS
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOU"."PK_DL_LWR_RATE_ASSESS_DETS" ON "HOU"."DL_HRA_LWR_RATE_ASSESS_DETS" ("LRAD_DLB_BATCH_ID", "LRAD_DL_SEQNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INDEXES" ;
--------------------------------------------------------
--  Constraints for Table DL_HRA_LWR_RATE_ASSESS_DETS
--------------------------------------------------------

  ALTER TABLE "HOU"."DL_HRA_LWR_RATE_ASSESS_DETS" MODIFY ("LRAD_RAAM_SEQ_NO" NOT NULL ENABLE);
  ALTER TABLE "HOU"."DL_HRA_LWR_RATE_ASSESS_DETS" MODIFY ("LRAD_CR_DR_INDICATOR" NOT NULL ENABLE);
  ALTER TABLE "HOU"."DL_HRA_LWR_RATE_ASSESS_DETS" MODIFY ("LRAD_CATEGORY_RATE_AMOUNT" NOT NULL ENABLE);
  ALTER TABLE "HOU"."DL_HRA_LWR_RATE_ASSESS_DETS" MODIFY ("LRAD_RCCO_CODE" NOT NULL ENABLE);
  ALTER TABLE "HOU"."DL_HRA_LWR_RATE_ASSESS_DETS" MODIFY ("LRAD_CLASS_CODE" NOT NULL ENABLE);
  ALTER TABLE "HOU"."DL_HRA_LWR_RATE_ASSESS_DETS" MODIFY ("LWRA_RATE_PERIOD_END_DATE" NOT NULL ENABLE);
  ALTER TABLE "HOU"."DL_HRA_LWR_RATE_ASSESS_DETS" MODIFY ("LWRA_RATE_PERIOD_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "HOU"."DL_HRA_LWR_RATE_ASSESS_DETS" MODIFY ("LRAD_WRA_CURR_ASSESSMENT_REF" NOT NULL ENABLE);
  ALTER TABLE "HOU"."DL_HRA_LWR_RATE_ASSESS_DETS" MODIFY ("LRAD_LWRB_REFNO" NOT NULL ENABLE);
  ALTER TABLE "HOU"."DL_HRA_LWR_RATE_ASSESS_DETS" MODIFY ("LRAD_DL_LOAD_STATUS" NOT NULL ENABLE);
  ALTER TABLE "HOU"."DL_HRA_LWR_RATE_ASSESS_DETS" MODIFY ("LRAD_DL_SEQNO" NOT NULL ENABLE);
  ALTER TABLE "HOU"."DL_HRA_LWR_RATE_ASSESS_DETS" MODIFY ("LRAD_DLB_BATCH_ID" NOT NULL ENABLE);
