--------------------------------------------------------
--  File created - Wednesday-September-26-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DL_HRA_LWR_WATER_METER_DETS
--------------------------------------------------------

  CREATE TABLE "HOU"."DL_HRA_LWR_WATER_METER_DETS" 
   (	"LWMD_DLB_BATCH_ID" VARCHAR2(30 BYTE), 
	"LWMD_DL_SEQNO" NUMBER(10,0), 
	"LWMD_DL_LOAD_STATUS" VARCHAR2(1 BYTE), 
	"LWMD_REFNO" NUMBER(10,0), 
	"LWMD_LWRB_REFNO" NUMBER(10,0), 
	"LWMD_WRA_CURR_ASSESSMENT_REF" VARCHAR2(20 BYTE), 
	"LWRA_RATE_PERIOD_START_DATE" DATE, 
	"LWRA_RATE_PERIOD_END_DATE" DATE, 
	"LWMD_RCCO_CODE" VARCHAR2(10 BYTE), 
	"LWMD_CURRENT_METER_READING" NUMBER(9,0), 
	"LWMD_PREVIOUS_METER_READING" NUMBER(9,0), 
	"LWMD_CHARGEABLE_WATER_USAGE" NUMBER(9,0), 
	"LWMD_CURRENT_READING_DATE" DATE, 
	"LWMD_PREVIOUS_READING_DATE" DATE, 
	"LWMD_DAYS_SINCE_LAST_READING" NUMBER(5,0), 
	"LWMD_WATER_METER_NUMBER" VARCHAR2(20 BYTE), 
	"LWMD_CREATED_BY" VARCHAR2(30 BYTE), 
	"LWMD_CREATED_DATE" DATE, 
	"LWMD_COMMENTS" VARCHAR2(240 BYTE), 
	"LWMD_MODIFIED_BY" VARCHAR2(30 BYTE), 
	"LWMD_MODIFIED_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TABLES" ;
--------------------------------------------------------
--  DDL for Index PK_DL_LWR_WATER_METER_DETAILS
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOU"."PK_DL_LWR_WATER_METER_DETAILS" ON "HOU"."DL_HRA_LWR_WATER_METER_DETS" ("LWMD_DLB_BATCH_ID", "LWMD_DL_SEQNO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INDEXES" ;
--------------------------------------------------------
--  Constraints for Table DL_HRA_LWR_WATER_METER_DETS
--------------------------------------------------------

  ALTER TABLE "HOU"."DL_HRA_LWR_WATER_METER_DETS" MODIFY ("LWMD_CHARGEABLE_WATER_USAGE" NOT NULL ENABLE);
  ALTER TABLE "HOU"."DL_HRA_LWR_WATER_METER_DETS" MODIFY ("LWMD_CURRENT_METER_READING" NOT NULL ENABLE);
  ALTER TABLE "HOU"."DL_HRA_LWR_WATER_METER_DETS" MODIFY ("LWMD_RCCO_CODE" NOT NULL ENABLE);
  ALTER TABLE "HOU"."DL_HRA_LWR_WATER_METER_DETS" MODIFY ("LWRA_RATE_PERIOD_END_DATE" NOT NULL ENABLE);
  ALTER TABLE "HOU"."DL_HRA_LWR_WATER_METER_DETS" MODIFY ("LWRA_RATE_PERIOD_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "HOU"."DL_HRA_LWR_WATER_METER_DETS" MODIFY ("LWMD_WRA_CURR_ASSESSMENT_REF" NOT NULL ENABLE);
  ALTER TABLE "HOU"."DL_HRA_LWR_WATER_METER_DETS" MODIFY ("LWMD_LWRB_REFNO" NOT NULL ENABLE);
  ALTER TABLE "HOU"."DL_HRA_LWR_WATER_METER_DETS" MODIFY ("LWMD_DL_LOAD_STATUS" NOT NULL ENABLE);
  ALTER TABLE "HOU"."DL_HRA_LWR_WATER_METER_DETS" MODIFY ("LWMD_DL_SEQNO" NOT NULL ENABLE);
  ALTER TABLE "HOU"."DL_HRA_LWR_WATER_METER_DETS" MODIFY ("LWMD_DLB_BATCH_ID" NOT NULL ENABLE);
