SET DEFINE OFF;
/*

    Insert HoL Business reasons

*/
Insert into PARAMETER_GROUPS (PGP_REFNO) values (pgp_refno_seq.nextval);
Insert into PARAMETER_GROUPS (PGP_REFNO) values (pgp_refno_seq.nextval);
Insert into BUSINESS_REASONS (BRO_CODE,BRO_DESCRIPTION,BRO_TYPE_IND,BRO_CURRENT_IND,BRO_BRC_CODE,BRO_ADDRESS_REQUIRED_IND,BRO_PARTY_OBJECT_IND,BRO_TENANCY_OBJECT_IND,BRO_PROPERTY_OBJECT_IND,BRO_CON_SITE_OBJECT_IND,BRO_APPLICATION_OBJECT_IND,BRO_ADMIN_UNIT_OBJECT_IND,BRO_INT_PTY_TYPE_OBJECT_IND,BRO_PEOPLE_GROUP_OBJECT_IND,BRO_LEASE_OBJECT_IND,BRO_SERV_REQ_OBJECT_IND,BRO_DEFAULT_SRC_PERSON_IND,BRO_DEFAULT_RESP_AU_IND,BRO_DEFAULT_SRC_ADDRESS_IND,BRO_WARNING_IND,BRO_PGP_CONTACT_REFNO,BRO_PGP_ACTION_REFNO,BRO_FRV_BRG_CODE,BRO_FRV_FCA_CODE,BRO_OVERALL_TARGET_DAYS,BRO_AUN_CODE,BRO_AUY_CODE,BRO_IPT_CODE,BRO_SYT_CODE,BRO_MODIFIED_BY,BRO_MODIFIED_DATE,BRO_SENSITIVE_IND,BRO_ADDR_TO_JROLE_REQ_IND,BRO_ADDR_TO_USER_NAME_REQ_IND,BRO_CONTACT_REQUIRED_IND,BRO_ACTION_ASSIGNED_TO_REQ_IND,BRO_DISPLAY_SEQUENCE,BRO_CONTACT_AU_REQ_IND,BRO_CONTACT_AUN_CODE,BRO_CONTACT_AUY_CODE,BRO_CODE_MLANG,BRO_DESCRIPTION_MLANG,BRO_LOAN_APP_OBJECT_IND,BRO_ORGANISATION_OBJECT_IND,BRO_DISPUTE_IND) values ('HOLCANAPP','Housing online cancel application','S','Y','ENQ','N','Y','N','N','N','N','N','N','Y','N','N','N','N','N','N',pgp_refno_seq.currval-1,pgp_refno_seq.currval,null,null,null,null,null,null,null,'NPSJDORSET',to_date('08/JUL/20','DD/MON/RR'),'N','N','N','N','N',null,'N',null,null,null,null,'N','N','N');
Insert into PARAMETER_GROUPS (PGP_REFNO) values (pgp_refno_seq.nextval);
Insert into PARAMETER_GROUPS (PGP_REFNO) values (pgp_refno_seq.nextval);
Insert into BUSINESS_REASONS (BRO_CODE,BRO_DESCRIPTION,BRO_TYPE_IND,BRO_CURRENT_IND,BRO_BRC_CODE,BRO_ADDRESS_REQUIRED_IND,BRO_PARTY_OBJECT_IND,BRO_TENANCY_OBJECT_IND,BRO_PROPERTY_OBJECT_IND,BRO_CON_SITE_OBJECT_IND,BRO_APPLICATION_OBJECT_IND,BRO_ADMIN_UNIT_OBJECT_IND,BRO_INT_PTY_TYPE_OBJECT_IND,BRO_PEOPLE_GROUP_OBJECT_IND,BRO_LEASE_OBJECT_IND,BRO_SERV_REQ_OBJECT_IND,BRO_DEFAULT_SRC_PERSON_IND,BRO_DEFAULT_RESP_AU_IND,BRO_DEFAULT_SRC_ADDRESS_IND,BRO_WARNING_IND,BRO_PGP_CONTACT_REFNO,BRO_PGP_ACTION_REFNO,BRO_FRV_BRG_CODE,BRO_FRV_FCA_CODE,BRO_OVERALL_TARGET_DAYS,BRO_AUN_CODE,BRO_AUY_CODE,BRO_IPT_CODE,BRO_SYT_CODE,BRO_MODIFIED_BY,BRO_MODIFIED_DATE,BRO_SENSITIVE_IND,BRO_ADDR_TO_JROLE_REQ_IND,BRO_ADDR_TO_USER_NAME_REQ_IND,BRO_CONTACT_REQUIRED_IND,BRO_ACTION_ASSIGNED_TO_REQ_IND,BRO_DISPLAY_SEQUENCE,BRO_CONTACT_AU_REQ_IND,BRO_CONTACT_AUN_CODE,BRO_CONTACT_AUY_CODE,BRO_CODE_MLANG,BRO_DESCRIPTION_MLANG,BRO_LOAN_APP_OBJECT_IND,BRO_ORGANISATION_OBJECT_IND,BRO_DISPUTE_IND) values ('HOLUPADD','Housing online update address details','S','Y','ENQ','Y','Y','N','N','N','N','N','N','Y','N','N','N','N','N','N',pgp_refno_seq.currval-1,pgp_refno_seq.currval,null,null,null,null,null,null,null,null,null,'N','N','N','N','N',null,'N',null,null,null,null,'N','N','N');
/*

    Insert ALLOTMENT address usage

*/
Insert into FIRST_REF_VALUES (FRV_FRD_DOMAIN,FRV_CODE,FRV_NAME,FRV_CURRENT_IND,FRV_USAGE,FRV_DEFAULT_IND) values ('ADDRESS_ROLES','ALLOTMENT','Allotment','Y','USR','N');
Insert into ADDRESS_USAGE_TYPES (AUT_FAO_CODE,AUT_FAR_CODE,AUT_USAGE,AUT_CURRENT_IND,AUT_FORMAT_IND,AUT_ALLOW_END_IND,AUT_ALLOW_CONTACT_NAME_IND) values ('PRO','ALLOTMENT','USR','Y','SIA','N','N');
