SET DEFINE OFF;
/*

    Insert ALLOTMENT address usage

*/
Insert into FIRST_REF_VALUES (FRV_FRD_DOMAIN,FRV_CODE,FRV_NAME,FRV_CURRENT_IND,FRV_USAGE,FRV_DEFAULT_IND) values ('ADDRESS_ROLES','ALLOTMENT','Allotment','Y','USR','N');
Insert into ADDRESS_USAGE_TYPES (AUT_FAO_CODE,AUT_FAR_CODE,AUT_USAGE,AUT_CURRENT_IND,AUT_FORMAT_IND,AUT_ALLOW_END_IND,AUT_ALLOW_CONTACT_NAME_IND) values ('PRO','ALLOTMENT','USR','Y','SIA','N','N');
