UPDATE users
SET usr_current_ind = 'N', USR_HTY_CODE = 'OLHHOU'
where usr_current_ind = 'Y'
and usr_username NOT in ('PVT_TORCAP_UNITYMAN', 'PVT_TORCAP_UNITYGEN', 'PVT_BENSUL_UNITYMAN', 'PVT_BENSUL_UNITYGEN', 'PVT_TIMGRO_UNITYMAN', 'PVT_TIMGRO_UNITYGEN', 'PVT_KIRMOY', 
                         'PVT_KELSAN', 'DAVLEW', 'JESMUR', 'ALAWAL', 'KAIXUE', 'KARSAN', 'EMIWRI', 'CHENOB', 'MATKAS', 'JANHOS', 
                         'CSO_PROFILE', 'MANSA_PROFILE', 'PCMOPS_PROFILE', 'ACCW_PROFILE', 'MAO_PROFILE', 
                         'MANCCU_PROFILE', 'RECOFFT_PROFILE', 'COMIPS_PROFILE', 'PROJSA_PROFILE', 'TACPRC_PROFILE', 'CEOFFICE_PROFILE', 'NRPPC_PROFILE', 'PAO_PROFILE', 'ALLO_PROFILE', 'TL_PROFILE', 
                         'HO_PROFILE', 'OM_PROFILE', 'CSOCC_PROFILE', 'CSOUT_PROFILE', 'OMCOUNTRY_PROFILE', 'SYSADM_PROFILE', 'TL_PROFILE', 'ACCW_PROFILE', 'TP_PROFILE')
AND USR_USERNAME NOT LIKE 'NPS%'
AND USR_USERNAME NOT LIKE '%PROFILE'
AND USR_USERNAME != 'SYSPRCONNECT'
AND USR_CORR_NAME IS NOT NULL;
